*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Aug 21 22:29:24 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 21 August 2018 13:40:08
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: iz2ze590m1lyedjw6m1v0lz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/app1
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/app1/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3889
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:1206 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Aug 21 2018, 21:34:37)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1c40b20
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1c40b20 pid: 9547 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 9547, cores: 1)
spawned uWSGI worker 2 (pid: 9549, cores: 1)
spawned uWSGI worker 3 (pid: 9550, cores: 1)
spawned uWSGI worker 4 (pid: 9551, cores: 1)
Internal Server Error: /blog/novel
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 1/1] 221.216.226.62 () {44 vars in 753 bytes} [Tue Aug 21 14:32:56 2018] GET /blog/novel => generated 62193 bytes in 43 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 1/2] 221.216.226.62 () {44 vars in 725 bytes} [Tue Aug 21 14:32:59 2018] GET /favicon.ico => generated 62175 bytes in 43 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /blog/novel/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 2/3] 221.216.226.62 () {44 vars in 755 bytes} [Tue Aug 21 14:33:12 2018] GET /blog/novel/ => generated 62205 bytes in 35 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 2/4] 221.216.226.62 () {44 vars in 726 bytes} [Tue Aug 21 14:33:12 2018] GET /favicon.ico => generated 62176 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /blog/novel/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 3/5] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 14:33:46 2018] GET /blog/novel/ => generated 62340 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 3/6] 221.216.226.62 () {48 vars in 779 bytes} [Tue Aug 21 14:33:46 2018] GET /favicon.ico => generated 62437 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /blog/novel/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 4/7] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 14:34:19 2018] GET /blog/novel/ => generated 62340 bytes in 56 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 4/8] 221.216.226.62 () {48 vars in 779 bytes} [Tue Aug 21 14:34:19 2018] GET /favicon.ico => generated 62437 bytes in 50 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 5/9] 221.216.226.62 () {44 vars in 745 bytes} [Tue Aug 21 14:37:39 2018] GET /admin/ => generated 62145 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 5/10] 221.216.226.62 () {44 vars in 721 bytes} [Tue Aug 21 14:37:39 2018] GET /favicon.ico => generated 62171 bytes in 33 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 6/11] 221.216.226.62 () {44 vars in 732 bytes} [Tue Aug 21 14:39:16 2018] GET / => generated 62066 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 6/12] 221.216.226.62 () {44 vars in 713 bytes} [Tue Aug 21 14:39:16 2018] GET /favicon.ico => generated 62157 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 7/13] 221.216.226.62 () {44 vars in 744 bytes} [Tue Aug 21 14:39:29 2018] GET /admin/ => generated 62138 bytes in 32 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 7/14] 221.216.226.62 () {44 vars in 719 bytes} [Tue Aug 21 14:39:30 2018] GET /favicon.ico => generated 62163 bytes in 35 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /blog/novel/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 8/15] 221.216.226.62 () {44 vars in 754 bytes} [Tue Aug 21 14:40:26 2018] GET /blog/novel/ => generated 62198 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 8/16] 221.216.226.62 () {44 vars in 724 bytes} [Tue Aug 21 14:40:27 2018] GET /favicon.ico => generated 62168 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /blog/novel/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 9/17] 221.216.226.62 () {46 vars in 785 bytes} [Tue Aug 21 14:53:52 2018] GET /blog/novel/ => generated 62333 bytes in 35 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 10/18] 221.216.226.62 () {48 vars in 777 bytes} [Tue Aug 21 14:53:52 2018] GET /favicon.ico => generated 62429 bytes in 36 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /blog/novel/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 11/19] 221.216.226.62 () {46 vars in 785 bytes} [Tue Aug 21 14:53:55 2018] GET /blog/novel/ => generated 62333 bytes in 35 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 9/20] 221.216.226.62 () {48 vars in 777 bytes} [Tue Aug 21 14:53:55 2018] GET /favicon.ico => generated 62429 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /blog/novel/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 12/21] 221.216.226.62 () {46 vars in 785 bytes} [Tue Aug 21 14:53:55 2018] GET /blog/novel/ => generated 62333 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 10/22] 221.216.226.62 () {48 vars in 777 bytes} [Tue Aug 21 14:53:55 2018] GET /favicon.ico => generated 62429 bytes in 36 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /blog/novel/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 13/23] 221.216.226.62 () {46 vars in 785 bytes} [Tue Aug 21 14:53:55 2018] GET /blog/novel/ => generated 62333 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 11/24] 221.216.226.62 () {48 vars in 777 bytes} [Tue Aug 21 14:53:56 2018] GET /favicon.ico => generated 62429 bytes in 35 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 14/25] 221.216.226.62 () {44 vars in 732 bytes} [Tue Aug 21 14:54:02 2018] GET / => generated 62066 bytes in 35 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 12/26] 221.216.226.62 () {44 vars in 713 bytes} [Tue Aug 21 14:54:03 2018] GET /favicon.ico => generated 62157 bytes in 35 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 15/27] 221.216.226.62 () {44 vars in 733 bytes} [Tue Aug 21 14:54:51 2018] GET / => generated 62073 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 13/28] 221.216.226.62 () {44 vars in 715 bytes} [Tue Aug 21 14:54:51 2018] GET /favicon.ico => generated 62165 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 16/29] 221.216.226.62 () {46 vars in 764 bytes} [Tue Aug 21 15:05:11 2018] GET / => generated 62208 bytes in 37 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 14/30] 221.216.226.62 () {48 vars in 768 bytes} [Tue Aug 21 15:05:11 2018] GET /favicon.ico => generated 62426 bytes in 38 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 17/31] 221.216.226.62 () {46 vars in 764 bytes} [Tue Aug 21 15:05:13 2018] GET / => generated 62208 bytes in 35 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 15/32] 221.216.226.62 () {48 vars in 768 bytes} [Tue Aug 21 15:05:13 2018] GET /favicon.ico => generated 62426 bytes in 34 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /blog/novel/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 18/33] 221.216.226.62 () {44 vars in 755 bytes} [Tue Aug 21 15:06:23 2018] GET /blog/novel/ => generated 62205 bytes in 35 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9550|app: 0|req: 16/34] 221.216.226.62 () {44 vars in 726 bytes} [Tue Aug 21 15:06:24 2018] GET /favicon.ico => generated 62176 bytes in 36 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /blog/novel/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/python3/lib/python3.6/site-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
[pid: 9551|app: 0|req: 19/35] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 15:07:19 2018] GET /blog/novel/ => generated *** Starting uWSGI 2.0.17.1 (64bit) on [Tue Aug 21 23:24:42 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 21 August 2018 13:40:08
os: Linux-3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
nodename: iz2ze590m1lyedjw6m1v0lz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/app1
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/app1/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3882
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:1206 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Aug 21 2018, 21:34:37)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ff0b20
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1ff0b20 pid: 1249 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1249, cores: 1)
spawned uWSGI worker 2 (pid: 1251, cores: 1)
spawned uWSGI worker 3 (pid: 1252, cores: 1)
spawned uWSGI worker 4 (pid: 1253, cores: 1)
Invalid HTTP_HOST header: '47.93.13.165:1700'. You may need to add '47.93.13.165' to ALLOWED_HOSTS.
[pid: 1253|app: 0|req: 1/1] 221.216.226.62 () {44 vars in 733 bytes} [Tue Aug 21 15:26:00 2018] GET / => generated 55266 bytes in 52 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '47.93.13.165:1700'. You may need to add '47.93.13.165' to ALLOWED_HOSTS.
[pid: 1251|app: 0|req: 1/2] 221.216.226.62 () {44 vars in 715 bytes} [Tue Aug 21 15:26:00 2018] GET /favicon.ico => generated 55358 bytes in 46 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '47.93.13.165:1700'. You may need to add '47.93.13.165' to ALLOWED_HOSTS.
[pid: 1253|app: 0|req: 2/3] 221.216.226.62 () {44 vars in 755 bytes} [Tue Aug 21 15:26:18 2018] GET /blog/novel/ => generated 55398 bytes in 38 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '47.93.13.165:1700'. You may need to add '47.93.13.165' to ALLOWED_HOSTS.
[pid: 1251|app: 0|req: 2/4] 221.216.226.62 () {44 vars in 726 bytes} [Tue Aug 21 15:26:18 2018] GET /favicon.ico => generated 55369 bytes in 33 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Aug 21 23:34:20 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 21 August 2018 13:40:08
os: Linux-3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
nodename: iz2ze590m1lyedjw6m1v0lz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/app1
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/app1/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3882
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:1206 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Aug 21 2018, 21:34:37)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1a9bb20
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1a9bb20 pid: 1165 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1165, cores: 1)
spawned uWSGI worker 2 (pid: 1167, cores: 1)
spawned uWSGI worker 3 (pid: 1168, cores: 1)
spawned uWSGI worker 4 (pid: 1169, cores: 1)
Not Found: /
[pid: 1167|app: 0|req: 1/1] 221.216.226.62 () {44 vars in 733 bytes} [Tue Aug 21 15:35:06 2018] GET / => generated 2029 bytes in 21 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 1169|app: 0|req: 1/2] 221.216.226.62 () {44 vars in 715 bytes} [Tue Aug 21 15:35:06 2018] GET /favicon.ico => generated 2080 bytes in 18 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
主页里的session
[pid: 1167|app: 0|req: 2/3] 221.216.226.62 () {44 vars in 755 bytes} [Tue Aug 21 15:35:15 2018] GET /blog/novel/ => generated 9402 bytes in 24 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1167|app: 0|req: 3/4] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 15:35:32 2018] GET /blog/novel/ => generated 9402 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 1167|app: 0|req: 4/5] 124.64.17.172 () {44 vars in 742 bytes} [Tue Aug 21 15:36:09 2018] GET /blog/novel => generated 0 bytes in 0 msecs (HTTP/1.1 301) 3 headers in 117 bytes (1 switches on core 0)
主页里的session
[pid: 1165|app: 0|req: 1/6] 124.64.17.172 () {44 vars in 744 bytes} [Tue Aug 21 15:36:10 2018] GET /blog/novel/ => generated 9402 bytes in 26 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1167|app: 0|req: 5/7] 124.64.17.172 () {44 vars in 744 bytes} [Tue Aug 21 15:36:14 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Aug 21 23:54:15 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 21 August 2018 13:40:08
os: Linux-3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
nodename: iz2ze590m1lyedjw6m1v0lz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/app1
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/app1/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3882
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:1206 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Aug 21 2018, 21:34:37)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2048b20
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x2048b20 pid: 1138 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1138, cores: 1)
spawned uWSGI worker 2 (pid: 1140, cores: 1)
spawned uWSGI worker 3 (pid: 1141, cores: 1)
spawned uWSGI worker 4 (pid: 1142, cores: 1)
Not Found: /
[pid: 1140|app: 0|req: 1/1] 221.216.226.62 () {44 vars in 733 bytes} [Tue Aug 21 15:54:52 2018] GET / => generated 2029 bytes in 28 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 1140|app: 0|req: 2/2] 221.216.226.62 () {44 vars in 753 bytes} [Tue Aug 21 15:55:24 2018] GET /blog/novel => generated 0 bytes in 0 msecs (HTTP/1.1 301) 3 headers in 117 bytes (1 switches on core 0)
主页里的session
[pid: 1141|app: 0|req: 1/3] 221.216.226.62 () {44 vars in 755 bytes} [Tue Aug 21 15:55:24 2018] GET /blog/novel/ => generated 9402 bytes in 45 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1140|app: 0|req: 3/4] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 15:56:01 2018] GET /blog/novel/ => generated 9402 bytes in 15 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1140|app: 0|req: 4/5] 124.64.17.172 () {44 vars in 744 bytes} [Tue Aug 21 15:56:13 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1140|app: 0|req: 5/6] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 16:00:12 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1142|app: 0|req: 1/7] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 16:00:13 2018] GET /blog/novel/ => generated 9402 bytes in 28 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1140|app: 0|req: 6/8] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 16:00:14 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1140|app: 0|req: 7/9] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 16:00:15 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1138|app: 0|req: 1/10] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 16:00:15 2018] GET /blog/novel/ => generated 9402 bytes in 22 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1140|app: 0|req: 8/11] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 16:00:15 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1142|app: 0|req: 2/12] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 16:00:16 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Aug 22 00:00:42 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 21 August 2018 13:40:08
os: Linux-3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
nodename: iz2ze590m1lyedjw6m1v0lz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/app1
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/app1/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3882
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:1206).
bind(): Address already in use [core/socket.c line 769]
主页里的session
[pid: 1140|app: 0|req: 9/13] 124.64.17.172 () {44 vars in 744 bytes} [Tue Aug 21 16:04:22 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1140|app: 0|req: 10/14] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 16:12:11 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1140|app: 0|req: 11/15] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 16:18:15 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1140|app: 0|req: 12/16] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 16:23:24 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1140|app: 0|req: 13/17] 124.64.17.172 () {44 vars in 744 bytes} [Tue Aug 21 16:28:14 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1140|app: 0|req: 14/18] 124.64.17.172 () {44 vars in 744 bytes} [Tue Aug 21 16:29:08 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Aug 22 00:42:41 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 21 August 2018 13:40:08
os: Linux-3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
nodename: iz2ze590m1lyedjw6m1v0lz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/app1
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/app1/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3882
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:1206 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Aug 21 2018, 21:34:37)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x110ab20
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x110ab20 pid: 1148 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1148, cores: 1)
spawned uWSGI worker 2 (pid: 1150, cores: 1)
spawned uWSGI worker 3 (pid: 1151, cores: 1)
spawned uWSGI worker 4 (pid: 1152, cores: 1)
主页里的session
[pid: 1150|app: 0|req: 1/1] 221.216.226.62 () {44 vars in 755 bytes} [Tue Aug 21 16:43:24 2018] GET /blog/novel/ => generated 9402 bytes in 33 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1150|app: 0|req: 2/2] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 16:57:29 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1150|app: 0|req: 3/3] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 16:57:44 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 1150|app: 0|req: 4/4] 221.216.226.62 () {46 vars in 786 bytes} [Tue Aug 21 17:00:56 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Aug 22 09:54:29 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 21 August 2018 13:40:08
os: Linux-3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
nodename: iz2ze590m1lyedjw6m1v0lz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/app1
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/app1/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3882
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:1206 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Aug 21 2018, 21:34:37)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xb84b20
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xb84b20 pid: 14149 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 14149, cores: 1)
spawned uWSGI worker 2 (pid: 14151, cores: 1)
spawned uWSGI worker 3 (pid: 14152, cores: 1)
spawned uWSGI worker 4 (pid: 14153, cores: 1)
Not Found: /
[pid: 14153|app: 0|req: 1/1] 39.155.157.50 () {44 vars in 730 bytes} [Wed Aug 22 01:55:40 2018] GET / => generated 2029 bytes in 43 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 14152|app: 0|req: 1/2] 39.155.157.50 () {44 vars in 712 bytes} [Wed Aug 22 01:55:42 2018] GET /favicon.ico => generated 2080 bytes in 88 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 14153|app: 0|req: 2/3] 39.155.157.50 () {44 vars in 750 bytes} [Wed Aug 22 01:56:01 2018] GET /blog/novel => generated 0 bytes in 0 msecs (HTTP/1.1 301) 3 headers in 117 bytes (1 switches on core 0)
主页里的session
[pid: 14149|app: 0|req: 1/4] 39.155.157.50 () {44 vars in 752 bytes} [Wed Aug 22 01:56:01 2018] GET /blog/novel/ => generated 9402 bytes in 96 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Aug 22 10:18:26 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 21 August 2018 13:40:08
os: Linux-3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
nodename: iz2ze590m1lyedjw6m1v0lz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/app1
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/app1/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3882
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:1206).
bind(): Address already in use [core/socket.c line 769]
主页里的session
[pid: 14153|app: 0|req: 3/5] 39.155.157.50 () {46 vars in 784 bytes} [Wed Aug 22 02:19:07 2018] GET /blog/novel/ => generated 9402 bytes in 24 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 4/6] 39.155.157.50 () {46 vars in 784 bytes} [Wed Aug 22 02:19:17 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 5/7] 39.155.157.50 () {46 vars in 784 bytes} [Wed Aug 22 02:22:57 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 6/8] 39.155.157.50 () {46 vars in 784 bytes} [Wed Aug 22 02:25:14 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 7/9] 39.155.157.50 () {46 vars in 784 bytes} [Wed Aug 22 02:26:48 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 8/10] 39.155.157.50 () {46 vars in 783 bytes} [Wed Aug 22 02:30:45 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 9/11] 39.155.157.50 () {46 vars in 784 bytes} [Wed Aug 22 02:30:55 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Aug 22 10:38:43 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 21 August 2018 13:40:08
os: Linux-3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
nodename: iz2ze590m1lyedjw6m1v0lz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/app1
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/app1/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3882
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:1206).
bind(): Address already in use [core/socket.c line 769]
主页里的session
[pid: 14153|app: 0|req: 10/12] 39.155.157.50 () {46 vars in 784 bytes} [Wed Aug 22 02:38:58 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /
[pid: 14153|app: 0|req: 11/13] 39.155.157.50 () {44 vars in 731 bytes} [Wed Aug 22 02:42:41 2018] GET / => generated 2029 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /
[pid: 14153|app: 0|req: 12/14] 39.155.157.50 () {46 vars in 762 bytes} [Wed Aug 22 02:42:55 2018] GET / => generated 2029 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 13/15] 39.155.157.50 () {44 vars in 753 bytes} [Wed Aug 22 02:47:18 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /
[pid: 14153|app: 0|req: 14/16] 39.155.157.50 () {44 vars in 731 bytes} [Wed Aug 22 02:47:26 2018] GET / => generated 2029 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 15/17] 39.155.157.50 () {44 vars in 753 bytes} [Wed Aug 22 02:47:46 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 14153|app: 0|req: 16/18] 39.155.157.50 () {44 vars in 741 bytes} [Wed Aug 22 02:47:55 2018] GET /admin => generated 0 bytes in 1 msecs (HTTP/1.1 301) 3 headers in 112 bytes (1 switches on core 0)
[pid: 14149|app: 0|req: 2/19] 39.155.157.50 () {44 vars in 743 bytes} [Wed Aug 22 02:47:55 2018] GET /admin/ => generated 0 bytes in 12 msecs (HTTP/1.1 302) 7 headers in 265 bytes (1 switches on core 0)
[pid: 14153|app: 0|req: 17/20] 39.155.157.50 () {44 vars in 780 bytes} [Wed Aug 22 02:47:55 2018] GET /admin/login/?next=/admin/ => generated 1855 bytes in 51 msecs (HTTP/1.1 200) 7 headers in 381 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 18/21] 39.155.157.50 () {46 vars in 842 bytes} [Wed Aug 22 02:48:14 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /static
[pid: 14153|app: 0|req: 19/22] 39.155.157.50 () {46 vars in 832 bytes} [Wed Aug 22 02:50:29 2018] GET /static => generated 2065 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 20/23] 39.155.157.50 () {46 vars in 842 bytes} [Wed Aug 22 02:53:56 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 21/24] 39.155.157.50 () {44 vars in 753 bytes} [Wed Aug 22 02:54:08 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 22/25] 39.155.157.50 () {44 vars in 753 bytes} [Wed Aug 22 02:58:09 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /
[pid: 14153|app: 0|req: 23/26] 39.155.157.50 () {48 vars in 851 bytes} [Wed Aug 22 02:58:23 2018] GET / => generated 2029 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 24/27] 39.155.157.50 () {46 vars in 842 bytes} [Wed Aug 22 02:58:37 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 25/28] 39.155.157.50 () {48 vars in 873 bytes} [Wed Aug 22 03:03:15 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 26/29] 39.155.157.50 () {48 vars in 873 bytes} [Wed Aug 22 03:06:13 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 27/30] 39.155.157.50 () {48 vars in 873 bytes} [Wed Aug 22 03:09:37 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 28/31] 39.155.157.50 () {44 vars in 753 bytes} [Wed Aug 22 03:09:59 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 29/32] 39.155.157.50 () {44 vars in 744 bytes} [Wed Aug 22 03:10:37 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 30/33] 39.155.157.50 () {44 vars in 744 bytes} [Wed Aug 22 03:13:41 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 31/34] 206.117.89.4 () {44 vars in 753 bytes} [Wed Aug 22 03:14:30 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 14153|app: 0|req: 32/35] 206.117.89.4 () {44 vars in 723 bytes} [Wed Aug 22 03:14:40 2018] GET /favicon.ico => generated 2080 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 33/36] 39.155.157.50 () {46 vars in 842 bytes} [Wed Aug 22 04:48:21 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 14153|app: 0|req: 34/37] 39.155.157.50 () {46 vars in 832 bytes} [Wed Aug 22 04:48:31 2018] GET /admin/ => generated 0 bytes in 1 msecs (HTTP/1.1 302) 7 headers in 265 bytes (1 switches on core 0)
[pid: 14151|app: 0|req: 1/38] 39.155.157.50 () {46 vars in 869 bytes} [Wed Aug 22 04:48:31 2018] GET /admin/login/?next=/admin/ => generated 1855 bytes in 45 msecs (HTTP/1.1 200) 7 headers in 381 bytes (1 switches on core 0)
[pid: 14153|app: 0|req: 35/39] 39.155.157.50 () {56 vars in 1122 bytes} [Wed Aug 22 04:48:53 2018] POST /admin/login/?next=/admin/ => generated 2031 bytes in 123 msecs (HTTP/1.1 200) 7 headers in 381 bytes (1 switches on core 0)
[pid: 14153|app: 0|req: 36/40] 39.155.157.50 () {46 vars in 869 bytes} [Wed Aug 22 04:49:03 2018] GET /admin/login/?next=/admin/ => generated 1855 bytes in 12 msecs (HTTP/1.1 200) 7 headers in 381 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 37/41] 114.242.249.198 () {44 vars in 746 bytes} [Wed Aug 22 06:30:00 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 38/42] 114.242.249.198 () {44 vars in 746 bytes} [Wed Aug 22 06:30:23 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 39/43] 114.242.249.198 () {44 vars in 746 bytes} [Wed Aug 22 10:30:36 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14152|app: 0|req: 2/44] 114.242.249.198 () {44 vars in 746 bytes} [Wed Aug 22 10:30:37 2018] GET /blog/novel/ => generated 9402 bytes in 13 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 40/45] 114.242.249.198 () {44 vars in 746 bytes} [Wed Aug 22 10:30:38 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 41/46] 114.242.249.198 () {44 vars in 746 bytes} [Wed Aug 22 10:40:02 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 42/47] 114.242.249.52 () {44 vars in 745 bytes} [Wed Aug 22 11:46:21 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 43/48] 114.242.249.52 () {44 vars in 745 bytes} [Wed Aug 22 11:47:08 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 44/49] 221.216.226.62 () {46 vars in 786 bytes} [Wed Aug 22 12:27:39 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 45/50] 221.216.226.62 () {46 vars in 786 bytes} [Wed Aug 22 12:27:53 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 46/51] 221.216.226.62 () {46 vars in 786 bytes} [Wed Aug 22 15:11:47 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 47/52] 221.216.226.62 () {46 vars in 786 bytes} [Wed Aug 22 16:12:45 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 48/53] 221.216.226.62 () {44 vars in 755 bytes} [Wed Aug 22 16:12:59 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /
[pid: 14153|app: 0|req: 49/54] 114.242.249.52 () {44 vars in 722 bytes} [Thu Aug 23 08:49:13 2018] GET / => generated 2029 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 14153|app: 0|req: 50/55] 114.242.249.52 () {44 vars in 732 bytes} [Thu Aug 23 08:49:26 2018] GET /admin => generated 0 bytes in 0 msecs (HTTP/1.1 301) 3 headers in 112 bytes (1 switches on core 0)
[pid: 14149|app: 0|req: 3/56] 114.242.249.52 () {44 vars in 734 bytes} [Thu Aug 23 08:49:26 2018] GET /admin/ => generated 0 bytes in 1 msecs (HTTP/1.1 302) 7 headers in 265 bytes (1 switches on core 0)
[pid: 14152|app: 0|req: 3/57] 114.242.249.52 () {44 vars in 771 bytes} [Thu Aug 23 08:49:26 2018] GET /admin/login/?next=/admin/ => generated 1855 bytes in 25 msecs (HTTP/1.1 200) 7 headers in 381 bytes (1 switches on core 0)
[pid: 14153|app: 0|req: 51/58] 114.242.249.52 () {54 vars in 1082 bytes} [Thu Aug 23 08:49:39 2018] POST /admin/login/?next=/admin/ => generated 2020 bytes in 103 msecs (HTTP/1.1 200) 7 headers in 381 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 52/59] 114.242.249.52 () {46 vars in 833 bytes} [Thu Aug 23 08:50:03 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 14153|app: 0|req: 53/60] 114.242.249.52 () {46 vars in 860 bytes} [Thu Aug 23 09:42:19 2018] GET /admin/login/?next=/admin/ => generated 1855 bytes in 12 msecs (HTTP/1.1 200) 7 headers in 381 bytes (1 switches on core 0)
Not Found: /
[pid: 14153|app: 0|req: 54/61] 114.242.249.52 () {46 vars in 811 bytes} [Thu Aug 23 09:49:18 2018] GET / => generated 2029 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 55/62] 114.242.249.52 () {46 vars in 833 bytes} [Thu Aug 23 09:49:25 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 56/63] 39.155.157.50 () {46 vars in 842 bytes} [Fri Aug 24 02:22:33 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 14152|app: 0|req: 4/64] 39.155.157.50 () {46 vars in 813 bytes} [Fri Aug 24 02:22:35 2018] GET /favicon.ico => generated 2080 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 57/65] 114.245.16.103 () {44 vars in 755 bytes} [Sat Aug 25 09:42:04 2018] GET /blog/novel/ => generated 9402 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 14153|app: 0|req: 58/66] 114.245.16.103 () {44 vars in 726 bytes} [Sat Aug 25 09:42:13 2018] GET /favicon.ico => generated 2080 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 14153|app: 0|req: 59/67] 114.245.16.103 () {44 vars in 755 bytes} [Sat Aug 25 09:42:50 2018] GET /favicon.ico => generated 2080 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
主页里的session
[pid: 14153|app: 0|req: 60/68] 114.245.16.103 () {44 vars in 755 bytes} [Sun Aug 26 16:35:43 2018] GET /blog/novel/ => generated 9402 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 14152|app: 0|req: 5/69] 114.245.16.103 () {44 vars in 726 bytes} [Sun Aug 26 16:35:45 2018] GET /favicon.ico => generated 2080 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
